name: Build exe

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions will run this job on an Ubuntu VM

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.4'  # Specify the Go version you are using

    - name: Build Windows executable
      run: |
        GOOS=windows GOARCH=amd64 go build -o push-${{github.run_number}}.exe
      # You can customize the output name or add additional build steps if needed

    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: push-${{github.run_number}}.exe

    - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: path_go.${{github.run_number}}
          artifacts:  push-${{github.run_number}}.exe